management:
  endpoints:
    web:
      exposure:
        #        don't expose all - *
        #        include: "*"
        include: [ "health","info","loggers","metrics","loggers","prometheus", "shutdown" ]
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
    tags:
      application: ${spring.application.name}