{
 "title": "Performance measurement",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "measurement_type",
    "label": "Measurement type",
    "query": "aop-annotation,aop-execution,bpp-cglib,bpp-dynamic,native,timed-micrometer,without-measurement"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (rate( delay_service_latency_seconds_bucket{type=\"native\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(delay_service_latency_seconds_sum{application=\"mega-application\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "IDK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(delay_service_latency_seconds_sum{application=\"mega-application\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "avg=sum/count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(delay_service_latency_seconds_sum{application=\"mega-application\"}[$__rate_interval])/rate(delay_service_latency_seconds_count{application=\"mega-application\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "IDK",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (label_replace(http_server_requests_seconds_sum{application=\"mega-application\", uri=~\"^/api/delay/.*\"}, \"type\", \"$1\", \"uri\", \"^/api/delay/(.+)$\") [$__rate_interval:] )",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"mega-application\", uri=\"/api/delay/without-measurement\"}[$__rate_interval])",
     "legendFormat": "without-measurement"
    }
   ]
  },
  {
   "title": "$measurement_type VS without measurement",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "repeat": "measurement_type",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate (http_server_requests_seconds_sum{application=\"mega-application\", uri=\"/api/delay/$measurement_type\"}[$__rate_interval] )",
     "legendFormat": "$measurement_type"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"mega-application\", uri=\"/api/delay/without-measurement\"}[$__rate_interval])",
     "legendFormat": "without-measurement"
    }
   ]
  }
 ]
}