global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: email-notifications
  routes:
    - matchers:
        - service="database"
      receiver: team-DB-pager
      # Also group alerts by affected database.
      group_by: [ alertname, cluster, database ]
      routes:
        - matchers:
            - owner="team-X"
          receiver: team-DB-pager
          continue: true

receivers:
  - name: "email-notifications"
    email_configs:
      - to: 'evgen.kuzmich@gmail.com'
  - name: "team-DB-pager"
    email_configs:
      - to: 'evgen.kuzmich@gmail.com'