groups:
  - name: alerts-mega-app
    rules:
      - alert: High scrape latency
        expr: topk(1, sum by (job) (scrape_duration_seconds)) > 0.4
        for: 1m
        labels:
          severity: warn
        annotations:
          summary: "High scrape latency on job {{ $labels.job }}"
          description: "The {{ $labels.job }} scrape job has high latency equals {{ $value }}s"
      - alert: High scrape latency for the 'mega-app-scraper-test' mega-app-scraper-test
        expr: scrape_duration_seconds{job="mega-app-scraper-test"} > 0.5
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Very high scrape latency on job {{ $labels.job }}"
          description: "The {{ $labels.job }} scrape job has VERY high latency equals {{ $value }}s"